version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - NODE_ENV=test
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
    depends_on:
      - gitlab
      - hydra
      - hydra-init
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local:8929'
        gitlab_rails['omniauth_enabled'] = true
        sidekiq['max_concurrency'] = 1
        puma['worker_processes'] = 0
        prometheus_monitoring['enable'] = false
    volumes:
      - ./data/gitlab/etc:/etc/gitlab
      - ./data/gitlab/log:/var/log/gitlab
      - ./data/gitlab/opt:/var/opt/gitlab
    ports:
      - "8929:8929"
      - "2222:22"
    shm_size: '256m'
  hydra:
    image: oryd/hydra:v2.2.0
    ports:
      - "4444:4444"
      - "4445:4445"
    environment:
      - DSN=memory
      - URLS_SELF_ISSUER=http://localhost:4444/
      - URLS_CONSENT=http://localhost:3000/test/auth/consent
      - URLS_LOGIN=http://localhost:3000/test/auth/login
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - URLS_ADMIN=http://localhost:4445/
    command:
      serve all --dev
  hydra-init:
    image: alpine:latest
    depends_on:
      - hydra
    volumes:
      - ./oauth-client.json:/oauth-client.json
      - ./oauth-client2.json:/oauth-client2.json
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    command: >
      sh -c "
        echo 'Hydraクライアント用のalpineコンテナ作成中...'
        apk add --no-cache curl jq
        echo 'Hydraサーバーの起動を待機中...'
        while ! curl -f http://hydra:4445/health/ready 2>/dev/null; do
          echo 'Hydraサーバーの起動を待機中...'
          sleep 5
        done
        echo 'Hydraサーバーが起動しました。OAuthクライアントを作成します...'
        if curl -s http://hydra:4445/admin/clients/70b01875-af94-499f-aa7c-ff63b71d7f4e 2>/dev/null | grep -q '70b01875-af94-499f-aa7c-ff63b71d7f4e'; then
          echo 'OAuthクライアントは既に存在します'
        else
          echo 'OAuthクライアントを作成中...'
          curl -X POST http://hydra:4445/admin/clients -H 'Content-Type: application/json' -d @/oauth-client.json
          echo ''
          echo 'OAuthクライアントが正常に作成されました！'
        fi
        if curl -s http://hydra:4445/admin/clients/d92b522a-a1cb-a2f1-a39f-c0fc12b6c4e9 2>/dev/null | grep -q 'd92b522a-a1cb-a2f1-a39f-c0fc12b6c4e9'; then
          echo 'OAuthクライアントは既に存在します'
        else
          echo 'OAuthクライアントを作成中...'
          curl -X POST http://hydra:4445/admin/clients -H 'Content-Type: application/json' -d @/oauth-client2.json
          echo ''
          echo 'OAuthクライアントが正常に作成されました！'
        fi
        echo 'Hydra初期化が完了しました！'
      "
    restart: "no"
