# GitHub Actions workflow for building, scanning, and pushing Docker image
# filepath: d:\devs\workspace202111\file-explorer-webapp\.github\workflows\docker-image.yml
name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/file-explorer-webapp:static

      - name: Scout Quickview
        uses: docker/scout-cli-action@v1
        with:
          scan-options: "quickview"

      - name: Test container runtime
        run: |
          docker run -d --name test-container -p 3000:3000 ghcr.io/${{ github.repository_owner }}/file-explorer-webapp:static
          sleep 5
          curl -f http://localhost:3000/api/list?path=/tmp
          docker rm -f test-container
